services:
  api:
    container_name: api
    build:
      context: .
      #dockerfile: ./utils/recipes/Dockerfile_app
      dockerfile: ./utils/recipes/Dockerfile_apache2
    volumes:
      #- ./api:/app
      - ./api:/var/www
      - ./utils/recipes/conf:/etc/apache2/sites-enabled
    ports:
      - "8002:80"
    environment:
      - SERVER_NAME=:80